#!/usr/bin/python3
"""
Module that factorizes as many numbers as possible
into a product of two smaller numbers.
"""

from sys import argv

def factorize(value):
    """
    Print a simple decomposition of an integer > 1.
    Args:
        value (int): The integer to be factorized.
    """
    i = 2

    if value < 2:
        return

    # Use trial division to find factors
    while value % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))

def main():
    """
    Main function to read numbers from a file and factorize them.
    """
    if len(argv) != 2:
        print("Usage: {} <filename>".format(argv[0]))
        exit("Incorrect usage. Please provide a filename.")

    try:
        with open(argv[1]) as file:
            line = file.readline()

            while line != "":
                value = int(line.strip())
                factorize(value)
                line = file.readline()
    except FileNotFoundError:
        exit(f"Error: File '{argv[1]}' not found.")
    except ValueError:
        exit("Error: Invalid content in the file. Please provide valid integers.")

if __name__ == "__main__":
    main()

